builds:
- id: "acar-appagent"
  dir: ./cmd/appagent
  binary: appagent
  goos:
  - linux
  goarch:
  - amd64
  - arm
  - arm64
  env:
  - CGO_ENABLED=0

- id: "acar-controlplane"
  dir: ./cmd/controlplane
  binary: controlplane
  goos:
  - linux
  goarch:
  - amd64
  - arm
  - arm64
  env:
  - CGO_ENABLED=0

- id: "acar-dataplane"
  dir: ./cmd/dataplane
  binary: dataplane
  goos:
  - linux
  goarch:
  - amd64
  - arm
  - arm64
  env:
  - CGO_ENABLED=0

- id: "acar-monitoring-server"
  dir: ./cmd/monitoring
  binary: monitoring-server
  goos:
  - linux
  goarch:
  - amd64
  - arm
  - arm64
  env:
  - CGO_ENABLED=0

- id: "acar-srnode-agent"
  dir: ./cmd/srnode-agent
  binary: srnode-agent
  goos:
  - linux
  goarch:
  - amd64
  - arm
  - arm64
  env:
  - CGO_ENABLED=0
