# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: controlplane.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from types import result_pb2 as types_dot_result__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='controlplane.proto',
  package='acar',
  syntax='proto3',
  serialized_options=b'Z\037github.com/chez-shanpu/acar/api',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12\x63ontrolplane.proto\x12\x04\x61\x63\x61r\x1a\x12types/result.proto\"Q\n\x07\x41ppInfo\x12\x10\n\x08\x61pp_name\x18\x01 \x01(\t\x12\x10\n\x08src_addr\x18\x02 \x01(\t\x12\x10\n\x08\x64st_addr\x18\x03 \x01(\t\x12\x10\n\x08sid_list\x18\x04 \x03(\t2E\n\x0c\x43ontrolPlane\x12\x35\n\x10RegisterSRPolicy\x12\r.acar.AppInfo\x1a\x12.acar.types.ResultB!Z\x1fgithub.com/chez-shanpu/acar/apib\x06proto3'
  ,
  dependencies=[types_dot_result__pb2.DESCRIPTOR,])




_APPINFO = _descriptor.Descriptor(
  name='AppInfo',
  full_name='acar.AppInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='app_name', full_name='acar.AppInfo.app_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='src_addr', full_name='acar.AppInfo.src_addr', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dst_addr', full_name='acar.AppInfo.dst_addr', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sid_list', full_name='acar.AppInfo.sid_list', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=129,
)

DESCRIPTOR.message_types_by_name['AppInfo'] = _APPINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AppInfo = _reflection.GeneratedProtocolMessageType('AppInfo', (_message.Message,), {
  'DESCRIPTOR' : _APPINFO,
  '__module__' : 'controlplane_pb2'
  # @@protoc_insertion_point(class_scope:acar.AppInfo)
  })
_sym_db.RegisterMessage(AppInfo)


DESCRIPTOR._options = None

_CONTROLPLANE = _descriptor.ServiceDescriptor(
  name='ControlPlane',
  full_name='acar.ControlPlane',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=131,
  serialized_end=200,
  methods=[
  _descriptor.MethodDescriptor(
    name='RegisterSRPolicy',
    full_name='acar.ControlPlane.RegisterSRPolicy',
    index=0,
    containing_service=None,
    input_type=_APPINFO,
    output_type=types_dot_result__pb2._RESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CONTROLPLANE)

DESCRIPTOR.services_by_name['ControlPlane'] = _CONTROLPLANE

# @@protoc_insertion_point(module_scope)
