# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import controlplane_pb2 as controlplane__pb2
from types import result_pb2 as types_dot_result__pb2


class ControlPlaneStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterSRPolicy = channel.unary_unary(
                '/acar.ControlPlane/RegisterSRPolicy',
                request_serializer=controlplane__pb2.AppInfo.SerializeToString,
                response_deserializer=types_dot_result__pb2.Result.FromString,
                )


class ControlPlaneServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterSRPolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControlPlaneServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterSRPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterSRPolicy,
                    request_deserializer=controlplane__pb2.AppInfo.FromString,
                    response_serializer=types_dot_result__pb2.Result.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'acar.ControlPlane', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ControlPlane(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterSRPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/acar.ControlPlane/RegisterSRPolicy',
            controlplane__pb2.AppInfo.SerializeToString,
            types_dot_result__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
