# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import dataplane_pb2 as dataplane__pb2
from types import result_pb2 as types_dot_result__pb2


class DataPlaneStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ApplySRPolicy = channel.unary_unary(
                '/acar.DataPlane/ApplySRPolicy',
                request_serializer=dataplane__pb2.SRInfo.SerializeToString,
                response_deserializer=types_dot_result__pb2.Result.FromString,
                )


class DataPlaneServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ApplySRPolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataPlaneServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ApplySRPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.ApplySRPolicy,
                    request_deserializer=dataplane__pb2.SRInfo.FromString,
                    response_serializer=types_dot_result__pb2.Result.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'acar.DataPlane', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DataPlane(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ApplySRPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/acar.DataPlane/ApplySRPolicy',
            dataplane__pb2.SRInfo.SerializeToString,
            types_dot_result__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
