# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dataplane.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from types import result_pb2 as types_dot_result__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='dataplane.proto',
  package='acar',
  syntax='proto3',
  serialized_options=b'Z\037github.com/chez-shanpu/acar/api',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x64\x61taplane.proto\x12\x04\x61\x63\x61r\x1a\x12types/result.proto\">\n\x06SRInfo\x12\x10\n\x08src_addr\x18\x01 \x01(\t\x12\x10\n\x08\x64st_addr\x18\x02 \x01(\t\x12\x10\n\x08sid_list\x18\x03 \x03(\t2>\n\tDataPlane\x12\x31\n\rApplySRPolicy\x12\x0c.acar.SRInfo\x1a\x12.acar.types.ResultB!Z\x1fgithub.com/chez-shanpu/acar/apib\x06proto3'
  ,
  dependencies=[types_dot_result__pb2.DESCRIPTOR,])




_SRINFO = _descriptor.Descriptor(
  name='SRInfo',
  full_name='acar.SRInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='src_addr', full_name='acar.SRInfo.src_addr', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dst_addr', full_name='acar.SRInfo.dst_addr', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sid_list', full_name='acar.SRInfo.sid_list', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=107,
)

DESCRIPTOR.message_types_by_name['SRInfo'] = _SRINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SRInfo = _reflection.GeneratedProtocolMessageType('SRInfo', (_message.Message,), {
  'DESCRIPTOR' : _SRINFO,
  '__module__' : 'dataplane_pb2'
  # @@protoc_insertion_point(class_scope:acar.SRInfo)
  })
_sym_db.RegisterMessage(SRInfo)


DESCRIPTOR._options = None

_DATAPLANE = _descriptor.ServiceDescriptor(
  name='DataPlane',
  full_name='acar.DataPlane',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=109,
  serialized_end=171,
  methods=[
  _descriptor.MethodDescriptor(
    name='ApplySRPolicy',
    full_name='acar.DataPlane.ApplySRPolicy',
    index=0,
    containing_service=None,
    input_type=_SRINFO,
    output_type=types_dot_result__pb2._RESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DATAPLANE)

DESCRIPTOR.services_by_name['DataPlane'] = _DATAPLANE

# @@protoc_insertion_point(module_scope)
