name: docker
on:
  push:
    branches:
    - main

jobs:
  test:
    strategy:
      matrix:
        platform: [ ubuntu-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push appagent
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: docker/appagent.Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/acar/appagent:latest

    - name: Build and push controlplane
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: docker/controlplane.Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/acar/controlplane:latest

    - name: Build and push dataplane
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: docker/dataplane.Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/acar/dataplane:latest

    - name: Build and push monitoring
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: docker/monitoring.Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/acar/monitoring:latest

    - name: Build and push srnode-agent
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: docker/srnode-agent.Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/acar/srnode-agent:latest