name: release-docker
on:
  push:
    tags:
    - '*'

jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.17.x ]
        platform: [ ubuntu-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Prepare for image tag
      id: prep
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        echo ::set-output name=version::${VERSION}

    - name: Build and push appagent
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: docker/appagent.Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/acar/appagent:stable
          ghcr.io/${{ github.repository_owner }}/acar/appagent:${{ steps.prep.outputs.version }}

    - name: Build and push controlplane
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: docker/controlplane.Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/acar/controlplane:stable
          ghcr.io/${{ github.repository_owner }}/acar/controlplane:${{ steps.prep.outputs.version }}

    - name: Build and push dataplane
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: docker/dataplane.Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/acar/dataplane:stable
          ghcr.io/${{ github.repository_owner }}/acar/dataplane:${{ steps.prep.outputs.version }}

    - name: Build and push monitoring-server
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: docker/monitoring-server.Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/acar/monitoring-server:stable
          ghcr.io/${{ github.repository_owner }}/acar/monitoring-server:${{ steps.prep.outputs.version }}

    - name: Build and push srnode-agent
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: docker/srnode-agent.Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/acar/srnode-agent:stable
          ghcr.io/${{ github.repository_owner }}/acar/srnode-agent:${{ steps.prep.outputs.version }}
